### ISSUE TITLE
Create Express Application

### ISSUE THREAD

**Issue by oliviergoulet5** [StudyMeet/StudyMeet#4]
## Description
As a developer I want to create a web server which supports REST APIs.

## Task
Create an express web application.

## Acceptance Criteria

- [x] Initialize express app
- [x] Add cors configuration
- [x] Listen on a port given in the environment variables; or else 8000.
