### ISSUE TITLE
Implement Continuous Integration

### ISSUE THREAD

**Issue by oliviergoulet5** [StudyMeet/StudyMeet#6]
## Description
As a developer I want continuous integration. This allows me to always have the ability to run a build of the web app or web server.

## Task
Choose a CI tool and install it.

## Acceptance Criteria

- [ ] CI has been chosen
- [ ] CI has been installed
- [ ] A build of the web server is running
- [ ] A build of the web app is running
