### ISSUE TITLE
Deploy Server

### ISSUE THREAD

**Issue by oliviergoulet5** [StudyMeet/StudyMeet#7]
## Description
As a developer I want to deploy a server.

## Task
Should deploy the web server in AWS. Should use Kubernetes, EC2 or EKS or something else. 

## Acceptance Criteria
- [ ] Web server is deployed
- [ ] Web server is containerized
- [ ] Web server is scalable
